name: "🐞 Bug Report"
description: "Report a bug to help us achieve greatness together!"
title: "Bug: "
labels: ["bug"]
assignees:
  - aviz92

body:
  - type: markdown
    attributes:
      value: |
        ## 🔧 Bug Description
        Please describe the bug clearly and concisely.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Step one
        2. Step two
        3. ...
      description: "List the steps required to reproduce the bug."
    validations:
      required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      placeholder: "What is currently happening?"

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      placeholder: "What did you expect to happen instead?"

  - type: textarea
    id: attachments
    attributes:
      label: Screenshots, Logs & Examples
      placeholder: "Attach screenshots, logs, or code snippets here."

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "e.g., macOS Sonoma / Chrome 123 / App v1.2.3"

  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions for Improvement/Fix (Optional)
      placeholder: "Any ideas on how to fix or improve it?"

  - type: input
    id: contact
    attributes:
      label: Contact Details (Optional)
      placeholder: "e.g., email, Discord, etc."

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      placeholder: "Any other helpful information?"
